# Generated by Django 4.0.6 on 2022-09-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
